### ISSUE TITLE
Overlap coefficient is not correct

### ISSUE THREAD

**Issue by reymondzzzz** [orsinium/textdistance#28]
In the implementation of the Overlap coefficient function, the intersection is divided by the minimum of the cardinality of the sets, and not the lengths of the sentences.
For example, "hello" and "world", coefficient = 0.5

`>>> textdistance.overlap("hello", "world")
0.4`

**Comment by orsinium** [comment]
Textdistance provides the same interface and default parameters for all algorithms. By default, all sequences compares by elements. You can compare them as sets with special argument:

```python
textdistance.Overlap(as_set=True)("hello", "world")
```

This is because for big enough sentences comparison as sets has no meaning and will produce close values (because alphabet for sentences will be almost the same).

**Comment by orsinium** [comment]
This is your first issue, congrats :)

**Comment by reymondzzzz** [comment]
Thanks for fast answer!
It's work. Thank you! Let's close this
